name: build and deploy to app service

on:
  push:
    branches:
      - prod
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Actions
      uses: actions/checkout@v2

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Plan and Apply Infrastructure
      working-directory: infra
      run: |
        terraform init
        terraform plan -out=tfplan
        terraform apply tfplan

        # Capture ACR output variables in a JSON file
        echo '{ "acr_name": "${azurerm_container_registry.example_acr.acr_name}", "acr_login_server": "${azurerm_container_registry.example_acr.login_server}", "acr_admin_username": "${azurerm_container_registry.example_acr.admin_username}", "acr_admin_password": "${azurerm_container_registry.example_acr.admin_password}", "app_service_name":"${azurerm_app_service.example_as.name}" }' > acr_outputs.json
  
    - name: Load ACR Output Variables
      run: |
        ACR_OUTPUTS=$(cat infra/acr_outputs.json)
        echo "$ACR_OUTPUTS" > "$GITHUB_ENV"

    - name: Set ACR URL and credentials
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/prod' ]]; then
          echo "APP_NAME=${{ env.app_service_name }}"" >> "$GITHUB_ENV"
          echo "APP_REPO=${{ env.acr_name }}" >> "$GITHUB_ENV"
          echo "ACR_URL=${{ env.acr_login_server }}" >> "$GITHUB_ENV"
          echo "ACR_USERNAME=${{ env.acr_admin_username }}" >> "$GITHUB_ENV"
          echo "ACR_PASSWORD=${{ env.acr_admin_password }}" >> "$GITHUB_ENV"
        fi

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_URL }}
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}

    - name: Build and push container image to ACR registry
      run: |
        docker build . -t ${{ env.ACR_URL }}/${{ env.APP_REPO }}:${{ github.sha }}
        docker push ${{ env.ACR_URL }}/${{ env.APP_REPO }}:${{ github.sha }}
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        images: '${{ env.ACR_URL }}/${{ env.APP_REPO }}:${{ github.sha }}'
        slot-name: ${{ github.ref_slug }}

    - name: Azure logout
      run: |
        az logout