name: Build and deploy to Azure App Service

on:
  push:
    branches:
      - Prod
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Actions
      uses: actions/checkout@v2

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set ENV Vars for TF
      run: |
        echo "export ARM_CLIENT_ID=${{ vars.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "export ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "export ARM_TENANT_ID=${{ vars.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "export ARM_SUBSCRIPTION_ID=${{ vars.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

    - name: Plan and Apply Infrastructure
      working-directory: infra
      run: |
        terraform init
        terraform plan -out=tfplan
        terraform apply tfplan

        # Capture output variables in a JSON file
        echo '{ "acr_name": "${azurerm_container_registry.example_acr.acr_name}", "acr_login_server": "${azurerm_container_registry.example_acr.login_server}", "acr_admin_username": "${azurerm_container_registry.example_acr.admin_username}", "acr_admin_password": "${azurerm_container_registry.example_acr.admin_password}", "app_service_name":"${azurerm_app_service.example_as.name}" }' > acr_outputs.json
  
    - name: Load ACR Output Variables to GitHub Environment
      run: |
        ACR_OUTPUTS=$(cat infra/acr_outputs.json)
        echo "$ACR_OUTPUTS" > "$GITHUB_ENV"

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.acr_login_server }}
        username: ${{ env.acr_admin_username }}
        password: ${{ env.acr_admin_password }}

    - name: Build and push container image to ACR registry
      run: |
        docker build . -t ${{ env.acr_login_server }}/${{ env.acr_name }}:${{ github.sha }}
        docker push ${{ env.acr_login_server }}/${{ env.acr_name }}:${{ github.sha }}
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app_service_name }}
        images: '${{ env.acr_login_server }}/${{ env.acr_name }}:${{ github.sha }}'
        slot-name: ${{ github.ref_slug }}

    - name: Azure logout
      run: |
        az logout