name: Build and deploy to Azure App Service

on:
  push:
    branches:
      - Prod
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Actions
      uses: actions/checkout@v2

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Plan and Apply Infrastructure
      working-directory: infra
      run: |
        terraform init
        terraform plan -out=tfplan
        terraform apply tfplan

    - name: Print $GITHUB_ENV
      run: env

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.acr_login_server }}
        username: ${{ env.acr_admin_username }}
        password: ${{ env.acr_admin_password }}

    - name: Build and push container image to ACR registry
      run: |
        docker build . -t ${{ env.acr_login_server }}/${{ env.acr_name }}:${{ github.sha }}
        docker push ${{ env.acr_login_server }}/${{ env.acr_name }}:${{ github.sha }}
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app_service_name }}
        images: '${{ env.acr_login_server }}/${{ env.acr_name }}:${{ github.sha }}'
        slot-name: ${{ github.ref_slug }}

    - name: Azure logout
      run: |
        az logout